-- MySQL Script generated by MySQL Workbench
-- Thu Apr  3 14:52:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CloudComputingDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CloudComputingDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CloudComputingDB` DEFAULT CHARACTER SET utf8 ;
USE `CloudComputingDB` ;

-- -----------------------------------------------------
-- Table `CloudComputingDB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CloudComputingDB`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `hashed_password` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CloudComputingDB`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CloudComputingDB`.`history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `query` LONGTEXT NULL,
  `historycol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_history_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_history_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `CloudComputingDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
